pore_type = "R9"
working_pore_percent = 85
target_yield = 100000000000
global_mean_read_length = 20000
random_seed = 10
output_path = "/tmp/"
vbz_plugin = "/data/dev/meta-gp/forks/icarust/vbz_plugin"

[parameters]

cert_dir = "/opt/ont/minknow/conf/rpc-certs/"
channels = 512
manager_port = 10000
position_port = 10001

sample_name = "test"
experiment_name = "test_human"
experiment_duration_set = 4800

device_id = "Device"
position = "MS12345"
flowcell_name = "FAQ12345"

break_read_ms = 400

[[sample]]
name = "CHM13v2 Chromosome1"
input_genome = "/tmp/squiggles/chr1.squiggle.npy"
mean_read_length = 15000
weight = 1

[[sample]]
name = "CHM13v2 Chromosome2"
input_genome = "/tmp/squiggles/chr2.squiggle.npy"
mean_read_length = 15000
weight = 1