FROM rust:1.69-bookworm

ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

ARG USERNAME
ARG UID
ARG GID

RUN groupadd -g ${GID} ${USERNAME} && useradd -u ${UID} -g ${GID} -s /bin/sh ${USERNAME} && mkdir -p /home/${USERNAME} && chown ${UID}:${GID} /home/${USERNAME}

WORKDIR /usr/src/icarust

# Protoc needs to be specific version for the MinKNOW API to compile (3.12) which is not available
# in the standard repositories on Ubunut 20.04 LTS - we are using a Debian container for this here

# Run as root for now, change to host container-user later
RUN apt update && apt-get -y install make cmake libprotobuf-dev protobuf-compiler musl-tools libzstd-dev git libcunit1 libcunit1-dev libhdf5-dev libopenblas-dev


# VBZ compression - need to figure out where this is needed in the Icarust compilation
RUN git clone https://github.com/nanoporetech/vbz_compression.git && cd vbz_compression && mkdir build && git submodule update --init && cd build && cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_CONAN=OFF -D ENABLE_PERF_TESTING=OFF -D ENABLE_PYTHON=OFF .. && make -j
RUN cp -r /usr/src/icarust/vbz_compression/vbz_plugin /vbz_plugin

# Run as host user, modify permissions of Cargo (container image)
USER ${USERNAME}

# This container is mainly used for generating R9 squiggles

WORKDIR /home/${USERNAME}
ENV PATH="${PATH}:/home/${USERNAME}/bin"

RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
RUN micromamba shell init --shell bash --root-prefix=~/micromamba

WORKDIR /usr/src/icarust