FROM nvidia/cuda:11.7.0-runtime-ubuntu22.04

RUN  apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    ca-certificates \
    build-essential \
    nvidia-cuda-toolkit \
    libhdf5-dev \
    libssl-dev \
    libzstd-dev \
    cmake \
    autoconf \
    automake