FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

ARG USERNAME
ARG UID
ARG GID

RUN groupadd -g ${GID} ${USERNAME} && useradd -u ${UID} -g ${GID} -s /bin/sh ${USERNAME} && mkdir -p /home/${USERNAME} && chown ${UID}:${GID} /home/${USERNAME}

ENV PATH="${PATH}:/opt/bin"
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    gdb \
    ca-certificates \
    build-essential \
    libhdf5-dev \
    libssl-dev \
    libzstd-dev \
    autoconf \
    automake \
    python3

WORKDIR /usr/src/dorado 

# RUN curl https://github.com/Kitware/CMake/releases/download/v3.27.0-rc3/cmake-3.27.0-rc3-linux-x86_64.sh --output /cmake-3.27.0-rc3-linux-x86_64.sh 
# RUN mkdir /opt/cmake
# RUN sh /cmake-3.27.0-rc3-linux-x86_64.sh --prefix=/opt/cmake --skip-license
# RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
# RUN cmake --version

ADD https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.5.3-linux-x64.tar.gz dorado-0.5.3-linux-x64.tar.gz
RUN tar xf dorado-0.5.3-linux-x64.tar.gz
RUN ln -s /usr/src/dorado/dorado-0.5.3-linux-x64/bin/dorado /usr/local/bin/dorado 

# Switching back to Dorado release versions

# Fails with `libdorado_torch_lib.so` errors in this image build

# RUN git clone --single-branch --branch v0.3.3 https://github.com/nanoporetech/dorado && \   
#     cd dorado && \
#     git config --global --add safe.directory "*" && \
#     cmake -S . -B cmake-build && \
#     cmake --build cmake-build --config Release -j4 && \ 
#     cmake --install cmake-build --prefix /opt/dorado 

# RUN ln -s /opt/dorado/bin/dorado /usr/local/bin/dorado

# Host user 
USER ${USERNAME}

# Add micromamba installation used in evaluation container which needs Dori access

WORKDIR /home/${USERNAME}
ENV PATH="${PATH}:/home/${USERNAME}/bin"

RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
RUN micromamba shell init --shell bash --root-prefix=~/micromamba

# Development path mounted, access to config files
WORKDIR /usr/src/streamfish 