version: "3.8"

services:

  # This builds a development container which mirrors the repository 
  # for cargo-watch auto-building on every change during development
  #
  #   docker-compose -f <compose-file> --profile dev --profile minknow --project-name <project> up <--build>
  #
  # For testing the terminal client while the development container
  # is running enter the running service container with:
  #
  #   docker exec -it <project>-reefsquid-dev-1 /bin/bash
  #
  # The compiled executable is copied to /usr/bin and available:
  #
  #   reefsquid test --help


  # This development container requires MinKnow to run on the host, it will
  # map the host ports into the container on `minknow_host` so that we can
  # connect to the MinKnow API. This requires to set the configuration 
  # environmental variable:
  #
  # REEFSQUID_MINKNOW_HOST=minknow_host
  #
  # This is done here with the environment variable which overrides the
  # configuration file (.env) from the shared directory tree

  reefsquid-dev:
    profiles:
      - dev
      - minknow
    image: reefsquid:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    environment:
      - REEFSQUID_MINKNOW_HOST=minknow_host
    extra_hosts:
      - "minknow_host:host-gateway"
    networks:
      - reefsquid
    volumes:
      - ../:/usr/src/reefsquid
      - /opt/ont/minknow/conf/rpc-certs/:/opt/ont/minknow/conf/rpc-certs/
    command: cargo watch -w src -w proto -w build.rs -w Cargo.toml -x "build --target x86_64-unknown-linux-musl --release && cp /usr/src/reefsquid/target/x86_64-unknown-linux-musl/release/reefsquid /usr/bin"

  dorado-dev:
    profiles:
      - dev
      - dorado
    image: dorado:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dorado.dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true   
    volumes:
      - ../dorado:/usr/src/reefsquid/dorado

networks:
  reefsquid: