FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04

ENV PATH="${PATH}:/opt/bin"
ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /usr/src/streamfish/dorado 

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    gdb \
    ca-certificates \
    build-essential \
    libhdf5-dev \
    libssl-dev \
    libzstd-dev \
    autoconf \
    automake \
    python3


ADD https://github.com/Kitware/CMake/releases/download/v3.27.0-rc3/cmake-3.27.0-rc3-linux-x86_64.sh /cmake-3.27.0-rc3-linux-x86_64.sh 
RUN mkdir /opt/cmake
RUN sh /cmake-3.27.0-rc3-linux-x86_64.sh --prefix=/opt/cmake --skip-license
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
RUN cmake --version

# COPY ../dorado ./

# # Development fork inside container
RUN git config --global --add safe.directory "*"


# RUN cmake -S . -B cmake-build
# RUN cmake --build cmake-build --config Release -j 4
# # remove tests with modified version
# # RUN ctest --test-dir cmake-build
# RUN cmake --install cmake-build --prefix /opt