[meta]
name            = 'streamfish-icarust-test'
version         = '0.1.0'
description     = 'Streamfish default configuration for Icarust testing'
  
[minknow]  
port            = 10000
host            = 'localhost' 
token           = 'ea953950-a67e-405b-ab3f-82bd728d0105'  
certificate     = '/opt/ont/minknow/conf/rpc-certs/ca.crt'

[icarust]  
enabled         = true
position_port   = 10001
sample_rate     = 4000

[dori]
tcp_enabled     = false
tcp_host        = '0.0.0.0'
tcp_port        = 10002
uds_path        = '/tmp/.dori/socket'
uds_override    = true

[dorado]  
batch_size      = 128
batch_timeout   = 100                                                                   # microseconds
model_runners   = 2

[readuntil]
dori_tcp_host   = 'dori-dev'                                                            # can be different outside container
dori_tcp_port   = 10002                                                                 # can be different outside container

[experiment]  
control         = false
mode            = 'mapping'
type            = 'targeted_sequencing'
reference       = '/tmp/bacteria.mmi'
targets         = ['NC_002516.2']                                                        # leave empty to target all sequences 
