[meta]
name                                    = 'streamfish-icarust-test'
version                                 = '0.1.0'
description                             = 'Streamfish default configuration for Icarust testing'

[minknow]       
port                                    = 10000                                                              # MinKNOW (9502) or Icarust (10000)
host                                    = 'localhost'                                                        # Address where this runs - if connecting from container (Dori) use the DoriConfig
token                                   = 'ea953950-a67e-405b-ab3f-82bd728d0105'  
certificate                             = '/opt/ont/minknow/conf/rpc-certs/ca.crt'

[icarust]       
enabled                                 = true
position_port                           = 10001
sample_rate                             = 4000

[dori]
tcp_enabled                             = false
tcp_host                                = '0.0.0.0'                                                          # `0.0.0.0` inside container to make available on forwarded ports
tcp_port                                = 10002
uds_path                                = '/tmp/.dori/socket'
uds_override                            = true
minknow_host                            = "minknow_host"                                                     # Host ports forwarded inside container
minknow_port                            = 10000                                                              # Manager service port inside container
basecaller_path                         = "/usr/src/streamfish/scripts/cpp/cmake-build/test"
basecaller_model                        = "/tmp/models/dna_r9.4.1_e8_fast@v3.4"
basecaller_stderr                       = "/tmp/dori.pipeline.stderr"

[dorado]  
batch_size                              = 128
batch_timeout                           = 1000                                                               # 1 ms
model_runners                           = 2
minimap_kmer_size                       = 15
minimap_window_size                     = 10

[readuntil]
device_name                             = "MS12345"
channel_start                           = 1
channel_end                             = 512
init_delay                              = 10
dori_tcp_host                           = 'dori-dev'                                                         # 'dori-dev' when running client inside container to connect to networked 'dori-dev' container, otherwise 'localhost' (port forwarded from inside container)
dori_tcp_port                           = 10002                                                              # '10002' when running client inside container, otherwise '10002' (port forwarded from inside container) - no changes necessary, should match `dori.tcp_port`
unblock_all                             = true
unblock_all_mode                        = "process"
read_cache                              = true
read_cache_batch_rpc                    = false
read_cache_min_chunks                   = 1
read_cache_max_chunks                   = 12
latency_log                             = "/tmp/latency.log"
throttle                                = 0                                                                  # Streaming actions (= 0) or batched actions (> 0) - in milliseconds
unblock_duration                        = 0.1
sample_minimum_chunk_size               = 200
accepted_first_chunk_classifications    = [83, 65]

[experiment]  
control                                 = false
mode                                    = 'mapping'
type                                    = 'targeted_sequencing'
reference                               = '/tmp/bacteria.mmi'
targets                                 = ['NC_002516.2']                                                    # leave empty to target all sequences 
