pore_type = "R9"
working_pore_percent = 85

target_yield = 100000000000
global_mean_read_length = 20000

random_seed = 10
output_path = "/tmp/"

[parameters]

sample_name = "test"
experiment_name = "test_bacteria"
experiment_duration_set = 4800

device_id = "Device"
position = "MS12345"
flowcell_name = "FAQ12345"

break_read_ms = 400

[[sample]]
name = "Bacteria 1"
input_genome = "squiggle_arrs/NC_002516.2.squiggle.npy" 
mean_read_length = 4000
weight = 1

[[sample]]
name = "Bacteria 2"
input_genome = "squiggle_arrs/NC_003997.3.squiggle.npy"
mean_read_length = 4000
weight = 1
