output_path = "/tmp"
target_yield = 100000000000
pore_type = "R10"
nucleotide_type = "DNA"
pod5 = true
vbz_plugin = "" # not pod5
kmer_model = "/data/dev/meta-gp/icarust/static/dna_r10.4.1_e8.2_400bps/R10_model.tsv"
prefix_squiggle = "/data/dev/meta-gp/icarust/static/prefix.squiggle.npy"

[parameters]
sample_name = "test"
experiment_name = "test_virus"
experiment_duration_set = 4800
device_id = "Device"
position = "MS12345"
flowcell_name = "FAQ12345"

break_read_ms = 400
sample_rate = 5000

cert_dir = "/data/dev/meta-gp/icarust/static/tls_certs"
channels = 512
manager_port = 10000
position_port = 10001

[[sample]]
name = "SARS-CoV-2 Wuhan 1"
input_genome = "/tmp/NC_045512.2.fasta" 
mean_read_length = 15000
weight = 1

[[sample]]
name = "MPXV Rivers"
input_genome = "/tmp/NC_063383.1.fasta"
mean_read_length = 15000
weight = 1