# Slice-and-dice configuration for multiple Streamfish clients and servers

# Note that Icarust should be run separately (rather than launched by the main routine) so that
# a single control server instance serves all slices, as expected in a real flowcell run with MinKNOW

channels                                = 2048
launch_dori_server                      = true  # recommended, otherwise manual setup necessary
launch_basecall_server                  = true  # recommended, otherwise manual setup necessary


[[slice]]
client_name                             = "StreamfishClient 1"
channel_start                           = 1
channel_end                             = 512
dori_adaptive_uds_path                  = '/tmp/.dori.adaptive/socket1'
basecaller_server_port                  = '/tmp/.basecaller_local/5556' 
basecaller_client_address               = 'ipc:///tmp/.basecaller_local/5556'

[[slice]]
client_name                             = "StreamfishClient 2"
channel_start                           = 513
channel_end                             = 1024
dori_adaptive_uds_path                  = '/tmp/.dori.adaptive/socket2'
basecaller_server_port                  = '/tmp/.basecaller_local/5557' 
basecaller_client_address               = 'ipc:///tmp/.basecaller_local/5557'

[[slice]]
client_name                             = "StreamfishClient 3"
channel_start                           = 1025
channel_end                             = 1536
dori_adaptive_uds_path                  = '/tmp/.dori.adaptive/socket3'
basecaller_server_port                       = '/tmp/.basecaller_local/5558' 
basecaller_client_address                    = 'ipc:///tmp/.basecaller_local/5558'

[[slice]]
client_name                             = "StreamfishClient 4"
channel_start                           = 1537
channel_end                             = 2048
dori_adaptive_uds_path                  = '/tmp/.dori.adaptive/socket4'
basecaller_server_port                  = '/tmp/.basecaller_local/5559' 
basecaller_client_address               = 'ipc:///tmp/.basecaller_local/5559'

