[meta]

name         = 'streamfish-default'
version      = '0.1.0'
description  = 'Streamfish default configuration as example'

[minknow]

port         = 9502
host         = 'localhost' 
token        = 'ea953950-a67e-405b-ab3f-82bd728d0105'  
certificate  = '/opt/ont/minknow/conf/rpc-certs/ca.crt'

[experiment]

mode         = 'mapping'
type         = 'targeted_sequencing'
reference    = '/tmp/chm13v2_ont.mmi'
targets      = ['chr1', 'chr3']  # leave empty to target all sequences 'chr5', 'chr7', 'chr9', 'chr11', 'chr13', 'chr15', 'chr17', 'chr19', 'chr21', 'chr23'
