[meta]
name                                    = 'streamfish-icarust-test'
version                                 = '0.1.0'
description                             = 'Streamfish default configuration for Icarust testing'
client_name                             = 'ReadfishClient'                                                   # Named for more informative messages in slice configurations
server_name                             = 'DoriServer'                                                       # Named for better distinction from client in terminal logs 

[minknow]       
host                                    = 'localhost'                                                        # Control server host - should always be 'localhost' for now
port                                    = 10000                                                              # Control server manager service port - defaults for MinKNOW (9502) or Icarust (10000)
token                                   = 'ea953950-a67e-405b-ab3f-82bd728d0105'                             # MinKNOW developer token for authentication
certificate                             = '/opt/ont/minknow/conf/rpc-certs/ca.crt'                           # MinKNOW certificate needed for MinKNOW and Icarust 

[icarust]       
enabled                                 = true                                                               # Uses MinKNOW configuration of host, port and certificate
position_port                           = 10001                                                              # Required position port to connect to device
sample_rate                             = 4000                                                               # Sample rate is currently not configuratble in Icarust, included for later modifications

[dori] 
uds_path                                = '/tmp/.dori/socket'                                                # Unix domain socket path on 'localhost', parent directory is created if not exists - SSD/NVME drives recommended, can be mounted in multiple containers for connections
uds_override                            = true                                                               # Allows overwriting an existing socket path
tcp_enabled                             = false                                                              # TCP connection to Dori processing server - not preferred
tcp_host                                = '0.0.0.0'                                                          # TCP server host - `0.0.0.0` inside container to make available on forwarded ports
tcp_port                                = 10002                                                              # TCP server port - can be mapped from container to host
minknow_host                            = "127.0.0.1"                                                        # Host port of control server (MinKNOW or Icarust) for access from Dori - if forwarded to container the value is `minknow_host` (docker/docker-compose.dev.yml)
minknow_port                            = 10000                                                              # Manager service port on `minknow_host` - this matches the `minknow.port` above but can be alternatively configured inside container
classifier                              = "minimap2-rs"                                                      # Classifier for adaptive sampling algorithm running on Dori [`minimap2-rs`]
basecaller                              = "guppy"                                                            # Basecaller fpr adapaitve sampling algorithm running through Dori [`guppy`]
stderr_log                              = "/tmp/dori.stderr"                                                 # Basecaller/classifier error output log as process is launched on Dori for now

[guppy.client]
path                                    = "/data/opt/conda/envs/guppy/bin/python"                            # "/home/esteinig/micromamba/envs/guppy/bin/python"
script                                  = "/data/dev/meta-gp/reefsquid/scripts/guppy/guppy_client.py"        # "/usr/src/streamfish/scripts/guppy/guppy_client.py"
address                                 = "ipc:///tmp/.guppy_local/5556"
config                                  = "dna_r9.4.1_450bps_fast"
throttle                                = 0.01                                                               # Receiver throttle for requests for completed reads
threads                                 = 4
max_reads_queued                        = 256

[guppy.server]
path                                    = "/opt/ont/guppy/bin/guppy_basecall_server" 
port                                    = "/tmp/.guppy_local/5556"
config                                  = "dna_r9.4.1_450bps_fast.cfg"
callers                                 = 4
chunks                                  = 160
threads                                 = 4
runners                                 = 8
device                                  = "cuda:all"
log_path                                = "/tmp/guppy.log"
stderr_log                              = "/tmp/guppy.stderr"

[minimap]

[readuntil]
device_name                             = "MS12345"
channels                                = 1024
channel_start                           = 1
channel_end                             = 1024
init_delay                              = 10
dori_tcp_host                           = 'dori-dev'                                                         # 'dori-dev' when running client inside container to connect to networked 'dori-dev' container, otherwise 'localhost' (port forwarded from inside container)
dori_tcp_port                           = 10002                                                              # '10002' when running client inside container, otherwise '10002' (port forwarded from inside container) - no changes necessary, should match `dori.tcp_port`
read_cache                              = true
read_cache_batch_rpc                    = false
read_cache_min_chunks                   = 1
read_cache_max_chunks                   = 12                                                   
latency_log                             = "/tmp/latency.log"
action_throttle                         = 0                                                                  # Streaming actions (= 0) or batched actions (> 0) - in milliseconds
unblock_duration                        = 0.1
sample_minimum_chunk_size               = 200
accepted_first_chunk_classifications    = [83, 65]
unblock_all                             = false
unblock_all_mode                        = "mapper"
launch_dori_server                      = true
launch_basecall_server                  = true

[experiment]  
control                                 = false
mode                                    = 'mapping'
type                                    = 'targeted_sequencing'
reference                               = '/tmp/chm13v2_chr11.mmi'
min_match_len                           = 0                                                           # minimum matched mapping length
targets                                 = ["chr11::9365480::9400673"]                                 # leave empty to target all sequences "NC_063383.1" - TMEM41B "chr11::9365480::9400673"