[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "ipc:///tmp/.guppy_local"
port = 5556

[conditions]
reference = "/tmp/viruses.mmi"

[conditions.0]
name = "viruses"
control = false
min_chunks = 0
max_chunks = 12
targets = ["NC_063383.1"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"