# Slice-and-dice configuration for Streamfish

channels                                = 2048

[[slice]]
channel_start                           = 1
channel_end                             = 1024
dori_uds_path                           = '/tmp/.dori1/socket'
guppy_server_address                    = 'ipc:///tmp/.guppy_local/5556'

[[slice]]
channel_start                           = 1025
channel_end                             = 2048
dori_uds_path                           = '/tmp/.dori2/socket'
guppy_server_address                    = 'ipc:///tmp/.guppy_local/5557'

