[meta]
name                                    = 'streamfish-icarust-test'
version                                 = '0.1.0'
description                             = 'Streamfish default configuration for Icarust testing'

[minknow]       
port                                    = 10000                                                              # MinKNOW (9502) or Icarust (10000)
host                                    = 'localhost'                                                        # Address where this runs - if connecting from container (Dori) use the DoriConfig
token                                   = 'ea953950-a67e-405b-ab3f-82bd728d0105'  
certificate                             = '/opt/ont/minknow/conf/rpc-certs/ca.crt'

[icarust]       
enabled                                 = true
position_port                           = 10001
sample_rate                             = 4000

[dori]
tcp_enabled                             = false
tcp_host                                = '0.0.0.0'                                                          # `0.0.0.0` inside container to make available on forwarded ports
tcp_port                                = 10002
uds_path                                = '/tmp/.dori2/socket'
uds_override                            = true
minknow_host                            = "minknow_host"                                                     # Host ports forwarded inside container
minknow_port                            = 10000                                                              # Manager service port inside container
classifier                              = "minimap2-rs"                                                      # minimap2-rs | kraken2 | minimap2-dorado (instable)
basecaller                              = "guppy"                                                            # guppy | dorado (instable)
basecaller_path                         = "/home/esteinig/micromamba/envs/guppy/bin/python"
basecaller_stderr                       = "/tmp/dori.pipeline.stderr"

[guppy]
client_path                             = "/usr/src/streamfish/scripts/guppy/guppy_client.py"
# client_throttle                         = 0.01
# client_threads                          = 8
# client_max_reads_queued                 = 256

server_address                          = "ipc:///tmp/.guppy_local/5557"
server_config                           = "dna_r9.4.1_450bps_fast"
# server_callers                          = 4
# server_chunk_size                       = 160
# server_ipc_threads                      = 8
# server_runners                          = 8


[minimap]
reference                               = '/tmp/viruses.mmi'
min_match_len                           = 0                                                                  # minimum matched mapping length for `minimap2-rs`

[readuntil]
device_name                             = "MS12345"
channels                                = 512
channel_start                           = 129
channel_end                             = 256
init_delay                              = 10
dori_tcp_host                           = 'dori-dev'                                                         # 'dori-dev' when running client inside container to connect to networked 'dori-dev' container, otherwise 'localhost' (port forwarded from inside container)
dori_tcp_port                           = 10002                                                              # '10002' when running client inside container, otherwise '10002' (port forwarded from inside container) - no changes necessary, should match `dori.tcp_port`
read_cache                              = true
read_cache_batch_rpc                    = false
read_cache_min_chunks                   = 1
read_cache_max_chunks                   = 12                                                    
latency_log                             = "/tmp/latency.log"
action_throttle                         = 0                                                                  # Streaming actions (= 0) or batched actions (> 0) - in milliseconds
unblock_duration                        = 0.1
sample_minimum_chunk_size               = 200
accepted_first_chunk_classifications    = [83, 65]
unblock_all                             = false
unblock_all_mode                        = "mapper"

[experiment]  
control                                 = false
mode                                    = 'mapping'
type                                    = 'targeted_sequencing'
targets                                 = ["NC_063383.1"]                                                    # leave empty to target all sequences "NC_063383.1"